### PR TITLE
don't use `is` on strings and look at all events

### PR DESCRIPTION
**Pull request by cmcmarrow**
Do not use `is` on strings. You should only use `is` when comparing to None `EX x is None`
Example https://stackoverflow.com/questions/2988017/string-comparison-in-python-is-vs
"""
x = "gos"
y = "go"
y  += "s"
print(x is y) # False
print(x == y) # True
"""

This should be the fix for your spacebar not working, let me know if its not the fix. 

Hopes this makes your day! 
For a 14 year old your doing very well! Keep up the good work!

If you want to make Terminal games check out my project https://github.com/cmcmarrow/tamcolors

### CODE REVIEW

**Comment by sudo-nikhil** [comment]
Hi! Now I understand the actual meaning of `is`. Unfortunately changing this didn't work. And by the way, (I should have mentioned this earlier) the code which is on my repo right now works on my laptop perfectly, whether it is `is` or `==`, but the problem is that when my friend tried cloning this and running this, everything worked except the space bar. This was really weird. Since i was a bit confused, i cloned my own repo and tried it again, suprisingly, the spacebar worked for me!! This ws how I became aware of this problem, I tried running this on my sister's laptop and the space bar didnt work even there! Now one thing I found in common was that my laptop had 4 cores and threads whereas, my sis's and my friend's laptop had 2 cores and 4 threads, will this be an issue?? I mean some nice guy on discord told me that the space bar worked on his laptop perfectly (since even he had 8 cores and 4 threads). He told me that the problem might be with threading or something. So is there any way to solve  #this?
Anyways, I really appreciate your effort and intention in trying to help me. Also thanks for your compliment. And even though the fix didn't work, you made my day, thanks!

**Comment by cmcmarrow** [comment]
I would try running it with == on your friends laptop is sometimes works. That's why it works on your laptop but not your friends .

**Comment by cmcmarrow** [comment]
you have an is on #117 which is when someone is trying to use the spacebar

**Comment by cmcmarrow** [comment]
your sisters laptop my get events in different orders than from yours
[10:35 AM]
Try my PR again... I'm pretty sure this is the fix now. My 24 Core PC does not have this bug, but not look at all event is a big problem

**Comment by sudo-nikhil** [comment]
> 
> 
> I would try running it with `==` on your friends laptop `is` sometimes works. That's why it works on your laptop but not your friends .

Hi i did run it with == instead of is. It didnt work.

**Comment by sudo-nikhil** [comment]
> 
> 
> your sisters laptop my get events in different orders than from yours
> Try my PR again... I'm pretty sure this is the fix now. My 24 Core PC does not have this bug, but not look at all event is a big problem

Yes, I will look into to it and let you know

**Pull request merged**
